### ISSUE TITLE
prescaler issue

### ISSUE THREAD

**Issue by Ribster** [4ilo/Wireless-Jukebox#1]
Olivier. Prescaler calculatie is (SystemCoreClock / gewenste frequentie) -1.
Uw calculatie voor 31KHz is dus normaal om (SystemCoreClock / 31000) -1 te berekenen..
Geen bug dus ;)

**Comment by 4ilo** [comment]
Ah, bedankt voor de reactie, vond het heel vreemd om de prescaler -1 te doen, maar toch goed om te weten dat het normaal is :)

Nog eens hartelijk bedankt.

**Comment by Ribster** [comment]
Jeps. Kijk eens in: [https://github.com/Ribster/PBEI-Project2/blob/master/ESHF0-0005-ALT0084_F072-NoWire_Pixel-A/src/application_leddim.c](url)
in application_leddim_uhPrescalerValue stel ik een frequency in van 40MHz.
Good luck!
